---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - multitenancy.1eedaegon.github.io
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multitenancy.1eedaegon.github.io
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - multitenancy.1eedaegon.github.io
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
