apiVersion: multitenancy.1eedaegon.github.io/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: tenant
    app.kubernetes.io/instance: tenant-sample
    app.kubernetes.io/part-of: tenant-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: tenant-operator
  name: tenant-sample
spec:
  # TODO(user): Add fields here
